type: bubble
subtype: 

# option to deactivate
active: true

# e.g. type: bar, subtype stacked ==> "bar (stacked)"

# Wikipedia article keyword to generate link e.g.:
# https://en.wikipedia.org/wiki/Scatter_plot
wiki_en: Bubble_chart
# Data Viz Catalogue method keyword to generate link e.g.:
# http://www.datavizcatalogue.com/methods/scatterplot.html
datavizcat: bubble_chart

# Brief description
description: "A scatter plot is a scatter plot in which each point displays a third variable in proportion to its area."

# Cover image for the card
cover: "bubble.png"
