type: violin
subtype: 

# option to deactivate
active: false

# e.g. type: bar, subtype stacked ==> "bar (stacked)"

# Wikipedia article keyword to generate link e.g.:
# https://en.wikipedia.org/wiki/Scatter_plot
wiki_en: Violin_plot
# Data Viz Catalogue method keyword to generate link e.g.:
# http://www.datavizcatalogue.com/methods/scatterplot.html
datavizcat:

# Brief description
description:

# Cover image for the card
cover: 
